### ISSUE TITLE
로그인 아닐 때 key page, my page, make-key page 진입시 랜딩페이지로

### ISSUE THREAD

**Issue by nonjee888** [SangGokSang/FE_puzzle_Godsang#107]
예외 페이지인 이용방법, 리스트 제외하고는 랜딩페이지로 가게 처리하기

**Comment by kangactor123** [comment]
로그인이 된 상태여도 주소창에 직접 mypage, create, key 를 검색해서 들어올 경우 landing 으로 리다이렉트 되도록 처리
