### ISSUE TITLE
광고 달기

### ISSUE THREAD

**Issue by bleuuue** [SangGokSang/FE_puzzle_Godsang#69]

**Comment by nonjee888** [comment]
광고버튼은 10초에 1회만 활성화 되어 볼 수 있음.

**Comment by nonjee888** [comment]
광고 팝업창 필요

**Comment by kangactor123** [comment]
광고는
이용방법, 편지보내기, 편지읽기, 키 만들기, 404 페이지에 넣어주시면 될 것 같습니다!

**Comment by kangactor123** [comment]
위치는
이용방법, 편지보내기, 편지읽기, 키 만들기: 하단
404 페이지: 로그인 버튼 위

에 들어가면 될 것 같아요!
